### ISSUE TITLE
Banning...

### ISSUE THREAD

**Issue by ElementProHD** [twizmwazin/CardinalPGM#1048]
I'm not sure where to put his as I'm fairly new to GitHub but I wanted to know when creating my own plugin is there a way of banning a player through cardinal using my own plugin. For example if I type /ban all in my plugin then it will ban these players through cardinal and say " >>You are permanently Banned". Thats just a example! 

Please help :)

**Comment by twizmwazin** [comment]
While In understand you have good intentions, this isn't a programming help forum, it is an issue tracker.

**Comment by CoWinkKeyDinkInc** [comment]
I don't think you're able to do that.

**Comment by twizmwazin** [comment]
We would need to abstract the command method to a method that could reasonably be called from anywhere, not just the command framework. Admittedly, that would be a better way of implementing it, however it wasn't something I thought of at the time. If you'd like to do so, feel free to make a module that handles Cardinal bans, and then modify the command to use that system rather than handling it itself.
