### ISSUE TITLE
1.7 Spigot Compatibility

### ISSUE THREAD

**Issue by BungeeTheCookie** [twizmwazin/CardinalPGM#1049]
Hello,

I'm not asking for you guys to do this, I am willing to take this on myself. I am just wondering, would it be fairly hard to take the SportBukkit 1.7 patches, apply them to Spigot, and then downgrade PGM 1.8.9 to 1.7.10? (Don't worry I'll include all the libraries and such)

@Pablete1234 

Thanks

**Comment by twizmwazin** [comment]
If you were to attempt this, I wouldn't reccomend using the last 1.8.9 build but rather the most recent version. The hard part would likely be porting the patches to spigot, although not difficult if you are experienced with it. The only difficulty I would for see in cardinal would be stripping out CTF unless you have a better solution. If you do attempt this, please share your results and experiences.

**Comment by BungeeTheCookie** [comment]
@twizmwazin 
Ah ok. I have a few questions (sorry I just came across Cardinal today, although I read up on ParaPGM in the past)

1.) Wouldn't it be harder to downgrade from 1.10 to 1.7.10, because of all of the Sound changes and the PVP changes in general?

2.) Why would I have to strip out CTF? Also, isn't CTF essentially CTW?

Thanks

**Comment by twizmwazin** [comment]
I would reccomend using a more recent version as a base because Cardinal 1 is a rolling release. New features are implemented as time goes on, many applicable to 1.7. Yes, there are a few bits you will need to work around (CTF,  Title Respawn) that you could avoid in an older version, but you also would have to rewrite or exclude  other features. There has been some minor API refactoring, but IntelliJ supports mass refactoring and I'd imaging eclipse would as well. The PVP changes are minor, look for Pablo's patches regarding them.

CTF uses armor stands and flags, both introduced in 1.8.

If you want the easiest route you could just use the last build of Sportbukkit 1.7.10 if you aren't concerned with spigot's patches.

**Comment by BungeeTheCookie** [comment]
Alrighty, 

Thank you so much!

**Comment by BungeeTheCookie** [comment]
@twizmwazin 
Should I use CardinalPGM 1.0 or start building on CardinalPGM 2.0 (from https://github.com/CardinalDevelopment/Cardinal)?

**Comment by twizmwazin** [comment]
Cardinal 1 is stable and feature rich, although contains a lot of older, less thought out code. Cardinal 2 is still really early in development, most features aren't written yet, but promises to be better thought out and more flexible. It is up to you which you want to use.

As a side note, Cardinal 2 currently isn't aiming for PGM compatibility, and as a result PGM was dropped from the name. Cardinal 1 is "CardinalPGM," Cardinal 2 is just "Cardinal."

**Comment by CoWinkKeyDinkInc** [comment]
So in other words, you're saying that Cardinal 2 will use a system separate from PGM's XML docs?  Would this still continue using XML or something more easier to write like JSON?  Good thing I heard of this, so I can get ready to port my map repo to Cardinal 2 when the first documentation comes.

**Comment by Pablete1234** [comment]
@CoWinkKeyDinkInc ATM the plan is not that clear, since ocn isn't shutting down anymore, but the original plan is to keep xml, and keep most of the structure, but remove outdated parts or inconsistencies, also we were going to keep each thing in it's tag, like all regions must be defined in the <regions> tag, and other improvements like some new things that we may want to add

**Comment by CoWinkKeyDinkInc** [comment]
That's pretty good, I can't wait to try out Cardinal 2 when it comes out!
