### ISSUE TITLE
Scoreboard still flashes

### ISSUE THREAD

**Issue by ItzWid13** [twizmwazin/CardinalPGM#193]
Video: http://youtu.be/mRN86pYLYlE

**Comment by AngelCasillas01** [comment]
The proximity should dissapear when you touch, on wools only when you placed, otherwise that scoreboard bug :c

**Comment by ParaPenguin** [comment]
The scoreboard flashes because a new scoreboard is registered every time an update is performed. This can be seen [here](https://github.com/twizmwazin/CardinalPGM/blob/039bd89ae931655537c35a5841cae8dd977da4c2/src/main/java/in/twizmwaz/cardinal/module/modules/gameScoreboard/GameScoreboard.java#L115-L120). You can fix this by using the `Score#resetScore()` method in Bukkit's API. This will reset the score, and remove it from the scoreboard, then you can add in the updated one. This means that you should only update scores that require an update, for example if an objective has been completed, you would update it from `✖ Monument` to `✔ Monument`, and any other objectives wouldn't be touched. This prevents the flashing, and also prevents some lag issues for some clients.

**Comment by ParaPenguin** [comment]
@twizmwazin I was about to see if I could fix this - but your GameScoreboard class was a little... cramped. You can fix it yourself <3

**Comment by twizmwazin** [comment]
@ParaPenguin I will gladly pass the blame on that one to Elly, I honestly have never done anything using scoreboards in Minecraft myself.

**Comment by iEli2tyree011** [comment]
@ParaPenguin ayy

**Comment by ItzWid13** [comment]
Please :c

**Comment by twizmwazin** [comment]
@ItzWid13 Be patient. All of the developers have things like school and jobs as well.

**Comment by iEli2tyree011** [comment]
Hopefully I can fix this tomorrow, since it seems to be a big issue. No promises though, I'm going to overhaul the scoreboard.

**Comment by TiTo-418** [comment]
Cant ParaPenguin resolved it?

**Comment by iEli2tyree011** [comment]
@TiTo-418 No...if you read what I said afterwards, the scoreboard system is not fit for what Para suggested, which is why I am redoing it. If you run a server on an appropriate amount of RAM, the server rarely flashes the scoreboard. Nevertheless, I'm still working on a fix for this.

**Comment by twizmwazin** [comment]
@TiTo-418 @iEli2tyree011 The CPU performance is also major factor, probably a larger factor here.

**Comment by ParaPenguin** [comment]
I think it's more of a network issue - it won't flash if you have low ping, but it will flash with higher ping because it takes longer for all of the packets to come through

**Comment by twizmwazin** [comment]
@ParaPenguin Do you know of anything we can do on the plugin-side to reduce this flashing?

**Comment by ParaPenguin** [comment]
Throw out your current Scoreboard system, then write a decent one that properly updates Scoreboard entries, by resetting the changed score, and setting a new one. This means you're not sending a load of wasted packets to the client, every time you update the scoreboard.

**Comment by twizmwazin** [comment]
@ParaPenguin That could have been phrased a little bit better, but I'll try to get that going this weekend.

**Comment by augustt198** [comment]
@ParaPenguin r00d

**Comment by ParaPenguin** [comment]
**Your way**
![Your way](http://i.imgur.com/EzLHZ0A.jpg)

**My way**
![My way](http://i.imgur.com/amDVVQ6.jpg)

@twizmwazin is that better explained? :smiley:

**Comment by twizmwazin** [comment]
@ParaPenguin I like the visuals. I understood it the first time though, the issue was with the implication that Elly's and my coding was not "decent."

**Comment by ParaPenguin** [comment]
I've done the same thing you're doing now many times, I only said it wasn't decent, because well... that specific area isn't. The rest of it I have no problem with, just the way you handle your scoreboards is bad for both the client, and the server it's running on. A couple of versions ago, your method would have caused large client lag for every player while the packets were sent out.

**Comment by TiTo-418** [comment]
ParaCardinalPGM

**Comment by MrTheSharpie** [comment]
Thankyou :D

**Comment by TiTo-418** [comment]
@iEli2tyree011 Still happen with the commit https://github.com/twizmwazin/CardinalPGM/commit/56f130203ef08312c5d35d8c1f2a4c9432496f80
