### ISSUE TITLE
Incorrect touch message in obs

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#481]
<a href="http://imgur.com/2uzfX0b"><img src="http://i.imgur.com/2uzfX0b.png" title="source: imgur.com" /></a>

Shoud be: [Player] damaged [objetive] for [Team]

**Comment by AngelCasillas01** [comment]
i think this is intentional :(

**Comment by TiTo-418** [comment]
It's wrong :(
TiTo_418 damaged Monument for the Impact 

:P

**Comment by twizmwazin** [comment]
It is correct, as normally it would say "for the Red Team," which is correct

**Comment by TiTo-418** [comment]
TiTo_418 damaged Monument for Red team

**Comment by SungMatt** [comment]
@TiTo-418 The use of the word "The" in English is referring to an object which is definite, like saying "The Interview". The example refers to a definite object, a particular interview. 

To leave out the "The" would be like saying 
"Dad, can I borrow car?" instead of "Dad, can I borrow the car?". The first example is broken English, and the recipient (Dad) would not know whose car I am borrowing, while the second refers to the car, which is his car.

As such, "the" is used in the statement.

**Comment by TiTo-418** [comment]
"Since Cardinal is for scrimmages, it wont show team names as "Red Team", will be "Oklahomies" as example."

**Comment by Prodigy4532** [comment]
"For The <name team>" is ugly ;c

http://gyazo.com/649c2724789e16fa1c5bfcd00158192d

**Comment by AngelCasillas01** [comment]
I think that on the TE PGM of OCN it's like this

**Comment by dentmaged** [comment]
```
TeamModule teamModule = ...;
String chatMessage = ...; // Get the message
if (!teamModule.getName().contains(" Team") {
    chatMessage = chatMessage.replace(" the", "");
}

**Comment by iEli2tyree011** [comment]
@dentmaged We're not hardcoding that, and we're not changing this regardless.
