### ISSUE TITLE
Tab issue

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#509]
Video proof: http://youtu.be/-udHx1xPBY4
Cardinal Version: 9593b9d6f8d3e9372c2ac1417cd94ed81cd70ede

**Comment by twizmwazin** [comment]
This isn't an issue with Cardinal itself, rather it is just how Minecraft handles the tab list.

**Comment by Superjd10** [comment]
@twizmwazin This may be an issue if he starts the match and the players that joined a team don't appear in the tab list.

**Comment by iEli2tyree011** [comment]
Player visibility is reset as soon as the match starts. I'll confirm this as soon as I get home.

**Comment by TiTo-418** [comment]
How it works on Overcast?

**Comment by dentmaged** [comment]
@TiTo-418 I think they have a custom packet handler which intercepts and changes the packet. I can't remember the name of the packet. Something like PacketOutPlayerList.

**Comment by twizmwazin** [comment]
@dentmaged It doesn't intercept and modify packets, it just doesn't send the normal packets and sends custom packets. If they did not have a custom tab list, it would work exactly the same way.

**Comment by TiTo-418** [comment]
So, when you close https://github.com/twizmwazin/CardinalPGM/issues/329 this issue will be fixed?

**Comment by twizmwazin** [comment]
Depends on how you define "fixed." This really isn't a bug in the first place.

**Comment by TiTo-418** [comment]
When i have the obs 'none' i will can see all the players in the tab?

**Comment by ryanw-ny** [comment]
Not sure if this pertains to the issue at hand, but I'm pretty sure Overcast Network does some manipulation to the tab list, for organization and data representation purposes. The Minecraft tab list should be organized by the ping (by the client), and the Overcast fixes this by just setting everyone's ping to the lowest bar. 

I don't really have access to a computer with Minecraft on it, since I'm having computer trouble but I am pretty sure even if you toggle the observers as hidden, you can still see them in the tab list on OCN.

**Comment by TiTo-418** [comment]
@ryanw-ny it is correct

**Comment by TiTi-418** [comment]
Look at this: http://youtu.be/Sb-Y8-K0q_A
