### ISSUE TITLE
Inconsistency when giving items to spectators

### ISSUE THREAD

**Issue by Pablete1234** [twizmwazin/CardinalPGM#562]
while on spectators, if someone does /minecraft:give on you, you get nothing.
it would make sense if spectators had fixed inventory, but that's not the case, spectators can modify their inventory as they wish (grabbing blocks from the creative menu) but the cannont get them via / give

**Comment by SungMatt** [comment]
@CaptainElliott The error is `command.give.notFound` in red, not a permissions issue.

**Comment by CaptainElliott** [comment]
I don't understand, could you show a screenshot?

**Comment by SungMatt** [comment]
@CaptainElliott My apologies, just realised that this only happens due to 1.8 id compatibility. This error is given iff the numerical ID is given as opposed to the `minecraft:<blockname>` .

If a numerical ID is given, this error occurs: 
![screen shot 2015-04-08 at 11 51 47 pm](https://cloud.githubusercontent.com/assets/6725727/7049281/ea55ee1c-de4a-11e4-868f-ac62eaf6ec92.png)

As Mojang has depreciated support for item IDs in 1.8, this is not an actual issue (Just a usage error)

Good night!

**Comment by iEli2tyree011** [comment]
Closing because @Pablete1234 didn't use the command correctly.

**Comment by Pablete1234** [comment]
i did not use the command wrongly, just try:
/give Pablete1234 stone 1

and i get nothing if i'm on spectator, but if i have joined the game i do get the item

**Comment by iEli2tyree011** [comment]
[Works fine for me.](http://i.imgur.com/CtiIAwl.png) What does it say in the chat when you do `/give Pablete1234 minecraft:stone 1?

**Comment by Pablete1234** [comment]
it says given 1 stone to pablete1234, but i don't get the item

**Comment by CaptainElliott** [comment]
Can we see both a screenshot of `/cardinal -v` and what happens after using the command?

**Comment by Pablete1234** [comment]
i'll do it when i go back home later

**Comment by CaptainElliott** [comment]
hang on, your using a 1.7 port on your server right?
https://oc.tc/forums/posts/552571eb5f35b9737b0027cf

**Comment by Pablete1234** [comment]
nope, i'm testing on 1.8

**Comment by Pablete1234** [comment]
maybe when i tested this (original post) it wasnt fixed yet and maybe it is now (for 1.8 version), i'll test it when i get home

**Comment by Pablete1234** [comment]
tested it and seems to be fine now (even on the 1.7 port), maybe it was broken when i first tested in a older version

**Comment by Pablete1234** [comment]
i found what the problem is, and this needs to be reopened.

the bukkit give command (/bukkit:give) does work fine
mojang give command(/minecraft:give) does not work

for whatever the reason is, minecraft give is not working, and i do prefer using minecraft give because you can set nbt tags.

**Comment by twizmwazin** [comment]
Why do you need to give items? Is the issue with Cardinal or SportBukkit?

**Comment by Pablete1234** [comment]
when i have joined a team i can /give perfectly fine, it's just while on observers, it says "[item] given to [player]" but you actually don't get the item

**Comment by ShinyDialga45** [comment]
Very strange. When coding Cardinal modules from a separate plugin, I had similar results. I tried to give an item to the player, but it was usually a ghost item and disappeared when I clicked on it.

**Comment by Pablete1234** [comment]
I think this is not fixed and should be reopened, or should i create a new issue being more specific on "minecraft:give" and not /give by itself?

**Comment by SungMatt** [comment]
I assume in order to reproduce it:
1. The command executor, "Giver", has to be in observers, and is an Operator on the server.
2. The receiver, "Recipient", has to be in observers. There is no difference between permission levels.
3. There is no need for the match to be running.
4. If the Giver executes `/minecraft:give <player> <item> [count] [data] [dataTag]` with all valid tags, the Recipient does not receive the item.

In my testing, 
using `/minecraft:give SungMatt minecraft:potion 1 16421 {CustomPotionEffects:[1:{Id:6,Amplifier:6,Duration:6}]}` , with the Giver being "SungMatt" and the Recipient being "SungMatt"

The Recipient is able to receive the proper item (Splash Potion of Healing, with a custom effect of "Instant Health potion.potency.6"), with its data tags.

Do tell us what command you are using, and the full method and prerequisites to reproduce this bug.

*Tested in CardinalPGM version `18a0ea8`*

**Comment by Pablete1234** [comment]
join my server, whine on observers:
/give [your name] stone
nothing happens

on commands.yml i have an alias for "give (any arguments)" ->minecraft:give (any arguments)

ps: while playing (joining a team different than observers) works fine

**Comment by SungMatt** [comment]
@Pablete1234 Hmm, I'm unable to recreate the issue. [Video](https://www.youtube.com/watch?v=rwejpUvMHS0)

**Comment by TiTo-418** [comment]
This isn't fixed :v

**Comment by Pablete1234** [comment]
i thought it was fixed but ok

**Comment by SungMatt** [comment]
@TiTo-418 @Pablete1234 Could you please verify if the bug is still a bug, or it is just incorrect usage? I am unable to recreate this bug, as I have said in the comment I made 2 months ago. Giving us a video would help, as none of us seem to be able to recreate this. Thanks.

**Comment by iEli2tyree011** [comment]
Also, make sure this isn't an issue of "ghost items".

**Comment by TiTo-418** [comment]
Sorry, it is fixed now, my bad

**Comment by Pablete1234** [comment]
when the issue was first created was not incorrect usage, the command gave back "ok message", so it   was not the command being wrongly executed.
i still think it maybe was related to inventory not  updating properly (ghost items), but it was also alot of times just items not appearing after /give.
i think it's fixed by now, closing again,
