### ISSUE TITLE
Matchstart and Cycling errors

### ISSUE THREAD

**Issue by youngpvprock** [twizmwazin/CardinalPGM#621]
The map "Dust" when start throw this -> http://pastebin.com/AN0j9f1W
Xml of the map ->http://pastebin.com/DLZZstCi

Two errors on cycle 
http://pastebin.com/9Agbwbwh --not related to cardinal
http://pastebin.com/sRnUsMA9

And i have other map with an error like the first map "Dust"

**Comment by Vixo1** [comment]
First line of the first pastebin, I think that you are using an old version of CardinalPGM
`[23:43:16] [Server thread/ERROR]: Could not pass event MatchStartEvent to Cardinal v1.0-SNAPSHOT-git-CardinalPGM-unknown
org.bukkit.event.EventException`

**Comment by iEli2tyree011** [comment]
Can you make the title of the issue relevant to what you're reporting?

**Comment by youngpvprock** [comment]
Just edited the name to Cardinal, don't like PGM in the name. Nothing important i think.

Edited the title.

**Comment by Vixo1** [comment]
You need to use default CardinalPGM to report errors, not edited versions...

**Comment by youngpvprock** [comment]
It's default, nothing edite, just a name. You can change it in plugin.yml dude

**Comment by twizmwazin** [comment]
@youngpvprock That is called editing the plugin guy

**Comment by youngpvprock** [comment]
@twizmwazin i do that, i take the plugin from here -> http://ci.twizmwaz.in/job/Cardinal/ then just change the name of the jar, open the plugin with winrar to have acces to plugin.yml and edit name to Cardinal. That's all.. It's not a real edited version just change the name to remove PGM
I just want to report errors so you can fix for all

**Comment by twizmwazin** [comment]
@youngpvprock Editing the name of a plugin can actually have unintended side effects, as the plugin is identified as such. The version you used to report this issue was not downloaded from my CI server, as the version is marked as unknown. While I appreciate you supporting us and reporting issues, be honest and don't lie.

**Comment by youngpvprock** [comment]
Well, you want i be honest, i just add autostart when there are 2 players in game. It perform the command start so it no affects to anything. Like i can see in the issue #618 are similar errors caused by the same thing. "Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0"

**Comment by MysticxPvP** [comment]
@youngpvprock Use an official version of Cardinal and try to replicate the error. (srry for my english)

**Comment by youngpvprock** [comment]
Take the error with the official vesion, it's same. I used this: http://ci.twizmwaz.in/job/Cardinal/190/
Error: http://pastebin.com/RxrRfHQU
If for each error i have to use official to confirm that the error exist, i'll do. I don't have problem, but the changes that i made don't affects to this kind of errors.

**Comment by dentmaged** [comment]
This issue seems to be related with the XML.

**Comment by iEli2tyree011** [comment]
This is definitely an issue with the XML. When you translated the XML to Spanish, you changed the team names. This resulted in the team IDs to default to `azul` and `rojo` instead of red and blue. However, the rest of the XML retains the reference towards the team IDs as `red` and `blue`. Either you need to specify the old IDs in the team element or you need to adjust all of the previous references to the teams.
