### ISSUE TITLE
Why i get this error?

### ISSUE THREAD

**Issue by RubeVi** [twizmwazin/CardinalPGM#640]
<a><img src="http://i.gyazo.com/3344cedb32e3a95956c6e76f611a885a.png"></img></a>

**Comment by iEli2tyree011** [comment]
What is the message when you mouse over it?

**Comment by RubeVi** [comment]
<a><img src="http://i.gyazo.com/725c8b097cf71132c10c3f1112025e49.png></img></a>

**Comment by Zenzoh** [comment]
1. You are using a map with blocks 36

2. You are using a modified version of Cardinal

**Comment by RubeVi** [comment]
@Zenzoh ninguna de las 2 xd

**Comment by Zenzoh** [comment]
@RubeVi You are using the latest version of Cardinal? Download in http://ci.twizmwaz.in/job/Cardinal/

**Comment by ryanw-ny** [comment]
@Zenzoh I don't think you get it, it appears he's trying to modify Cardinal for development purposes. He's getting a error with the getBlocks() method, which is why he created the issue. If this is also present in the regular source code and isn't a client error, then this is a valid issue.

Telling him he's using a modified version of cardinal and a map with block 36 then telling him the download for the jar version of Cardinal isn't going to help him with the issue.

@RubeVi Make sure you imported all of the proper dependencies with maven, also try refreshing the project and check to make sure that it isn't a user inflicted error on your part.

**Comment by iEli2tyree011** [comment]
@RubeVi What IDE are you using?

**Comment by twizmwazin** [comment]
This is clearly a dependency issue, are you using sportbukkit, and is it being imported via maven? Despite the IDE error, does it cleanly compile?

Closing as this isn't technically a Cardinal issue, feel free to continue discussion

**Comment by RubeVi** [comment]
i have all the dependencys of the POM.xml

**Comment by dentmaged** [comment]
@Zenzoh Whether or not the map has block 36 in it, it wouldn't cause that error.

**Comment by twizmwazin** [comment]
@RubeVi Does it cleanly compile with maven?

**Comment by RubeVi** [comment]
yes i have it 
a pic http://gyazo.com/79fd66e1a64f930f3ddb27b45bf8551e

**Comment by CaptainElliott** [comment]
@RubeVi That does not answer twiz's question, can you compile the plugin cleanly?

**Comment by twizmwazin** [comment]
@RubeVi It looks like you aren't using sportbukkit off maven. Are you trying to use a custom version?

**Comment by dentmaged** [comment]
@twizmwazin Eclipse can be glitchy an often saving a file during compiling with maven can cause a lot of ghost errors.

**Comment by RubeVi** [comment]
@twizmwazin yes, i can compile cleanly with maven

**Comment by RubeVi** [comment]
@twizmwazin is the SportBukkit off maven but i only change the name

**Comment by dentmaged** [comment]
@RubeVi In the pom.xml?

**Comment by RubeVi** [comment]
yes @dentmaged

**Comment by dentmaged** [comment]
@RubeVi Did you update all references in Cardinal's pom.xml?

**Comment by RubeVi** [comment]
i'm going to do that

**Comment by RubeVi** [comment]
OHH, FIXED! THANKS 4 SUPPORT GUYS!
