### ISSUE TITLE
Update TDM scoreboard

### ISSUE THREAD

**Issue by Alfalik** [twizmwazin/CardinalPGM#698]
TDM scoreboard has been changed and now looks like this list of images.

+ Image 1: http://gyazo.com/f1dd08535ecd362eb9fe71af79d4e316
+ Image 2: http://gyazo.com/63614b2dd73458b80b20c1529bd6fa5f
+ Image 3: http://gyazo.com/c830c54d3b5bd6e811dc497cafc31ed9

**Comment by iEli2tyree011** [comment]
I'll try and get to this today.

**Comment by iEli2tyree011** [comment]
Since I'm currently updating the `teams` branch to adjust the scoreboard to the new optional teams system, I'm going to change this alongside the other scoreboard changes. I don't recommend using that branch for your plugin, as it's not tested and doesn't even build yet, but once we convert over a few more things we should be set to merge it to master.
