### ISSUE TITLE
server doenst load plugin, after crash, and reboot

### ISSUE THREAD

**Issue by kroest** [twizmwazin/CardinalPGM#793]
i let a lof my people use my server, but the server crashes fairly often, (most of the time by cycling to the same map), and when the server reboots, it doesnt load cardinal. If i remove the database and config file, the plugin does load again, but this is a big pain in the ass for me since the server is down a few hours after i fixed it.

server log: http://pastebin.com/hiL9VyvX

**Comment by TiTo-418** [comment]
Related with https://github.com/twizmwazin/CardinalPGM/issues/789?

**Comment by TiTo-418** [comment]
Update you <a href="http://ci.twizmwaz.in/job/Cardinal/lastSuccessfulBuild/">Cardinal</a> and <a href="https://repo.oc.tc/content/repositories/snapshots/tc/oc/sportbukkit/1.8.7-R0.1-SNAPSHOT/sportbukkit-1.8.7-R0.1-20150719.205709-24.jar">Sportbukkit</a>

**Comment by twizmwazin** [comment]
You are using an outdated, unknown version of Cardinal. Download the latest build off my server, and see if your issue is resolved. I'm going to close this for now until you confirm it is still broken. Try removing the bad map and if it is a cardinal issue report it as such.

**Comment by kroest** [comment]
this is a version from like 3 days ago, i only edited the server modt.

**Comment by kroest** [comment]
i still experience this issue, http://pastebin.com/xmzyfRyB

**Comment by iEli2tyree011** [comment]
You are using a lot of broken XMLs...whereever it says "Failed to load map at ...", that means a map usually doesn't have a proper XML file assosciated with the map. For example, your maps `LarrowH` and `GD3` don't have working XMLs, just due to plain formatting issues. Also, one of your plugins isn't loading properly; `AlwaysOnline`. Cardinal isn't expected to be compatible with everything, nor was it made to be compatibile with everything. Try temporarirly removing this plugin because it has an invalid plugin.yml, which basically contains all the information about the plugin for the Bukkit server. Fix these things then get back to us.

**Comment by Prodigy4532** [comment]
Only use "CardinalPGM" And "World Edit"
You can find other compatible plugin here:
https://meocloud.pt/link/fff681c6-3cf4-4ce7-bf2f-3bb2645cde3e/Plugins%20Externos/

**Comment by Pablete1234** [comment]
@iEli2tyree011 even if there are broken xml's, they get skipped, that's been the case for my server forever and has never been an issue, it just prints out a warn, and forgets about them

**Comment by kroest** [comment]
@iEli2tyree011  ill remove it just for you, but i installed it yesterday and i experience this issue all the time i used cardinal.

**Comment by iEli2tyree011** [comment]
@Pablete1234 I never said my changes would fix them, and I know they most likely won't, I just want to identify a source for the problem because obviously there's something not working right here.

**Comment by twizmwazin** [comment]
AlwaysOnline is a bungee plugin, not a bukkit plugin. It won't work on bukkit server.

**Comment by TiTo-418** [comment]
@twizmwazin Do you plan implement some AlwaysOnline funtions in Cardinal?

**Comment by ryanw-se** [comment]
@TiTo-418 All that plugin does is check if the IP from your previous join is the same as your current join and if so it lets you join, otherwise it doesn't. It also doesn't allow new players to join when the server is down, basically its offline mode with IP auth.

**Comment by twizmwazin** [comment]
@TiTo-418 definitely not

**Comment by Pablete1234** [comment]
@twizmwazin you said there is a local database for author names, but when mojang servers are down the server fails to startup (because it needs some data from mojang or something), it would be nice if cardinal could still work when mojang servers are down, via a local database, i think tito is refering to that more than player auth by ip

**Comment by TiTo-418** [comment]
@twizmwazin 
> AlwaysOnline is a bungee plugin, not a bukkit plugin. It won't work on bukkit server.
That is incorrect https://www.spigotmc.org/resources/alwaysonline.820/update?update=36775

**Comment by twizmwazin** [comment]
@TiTo-418 I'm not sure if they support craftbukkit though. It may use a spigot feature not found on craftbukkit and sportbukkit
