### ISSUE TITLE
Implemente an autostart system

### ISSUE THREAD

**Issue by DaniOurGamer** [twizmwazin/CardinalPGM#796]
Hi, I want to ask  if you can implement an autostart. Because some times members of my team enter and they can't play and I dont want to give them a rank. So I want to ask if you can create  for me a system like when they are 1 member in each team , the match starts. Thanks so much

**Comment by Pablete1234** [comment]
Maybe /ready? if both teams ready the match will start

**Comment by TiTo-418** [comment]
Cardinal doesn't support networks
Also, look at previous issues https://github.com/twizmwazin/CardinalPGM/issues/362

**Comment by dentmaged** [comment]
You aren't even on a team. If you do own a team, give yoir teammates op/mod or use the new rank system.

**Comment by twizmwazin** [comment]
This was open for consideration. Now that I know you just want to make a network, no, fuck off. Why can't people just grow up and do something themselves rather than take my plugin to try and clone another server. There are so many ideas to make servers, but instead too many people insist on making horrible knockoffs of OCN, often time giving absolutely no credit to who made 99% of their plugin, claiming it was their own.

**Comment by dentmaged** [comment]
@twizmwazin *cough cough* MineLC
