### ISSUE TITLE
You can destroy your own wool after placed.

### ISSUE THREAD

**Issue by Brokennz** [twizmwazin/CardinalPGM#902]

**Comment by Brokennz** [comment]
![screenshot_2](https://cloud.githubusercontent.com/assets/11890645/10348684/2ae877ee-6d00-11e5-8d95-3ce0804c63d3.png)

**Comment by Pablete1234** [comment]
you shouldn't be able to:
https://github.com/twizmwazin/CardinalPGM/blob/master/src/main/java/in/twizmwaz/cardinal/module/modules/wools/WoolObjective.java#L238
i'll dig a bit more into this tomorrow

**Comment by TiTo-418** [comment]
Map?

**Comment by Brokennz** [comment]
NextGen TE, Deepwind Jungle, Golden Drought III & Ring Race

**Comment by Alfalik** [comment]
Drop the wool on the void or break the block on victory monument after placed?

**Comment by Brokennz** [comment]
Drop the wool into the void after placed.

**Comment by twizmwazin** [comment]
I'm not entirely sure what the issue is here, as no description is provided. Should cardinal be stopping you from throwing wool blocks into the void after they are placed? Or is the issue that you are given snowflakes? Please be more descriptive. If you don't know how to describe the issue in English, a video also works.

**Comment by Pablete1234** [comment]
@twizmwazin i think he means that you get raindrops for destroing a wool that has been placed, i'll fix it

**Comment by twizmwazin** [comment]
oh ok

**Comment by twizmwazin** [comment]
fixed in 14a945c5ee8344a96757085941058bcad9ebc578
