### ISSUE TITLE
[CardinalPGM] Task #5 for Cardinal v1.0-SNAPSHOT-git-CardinalPGM-1e380db generated an exception

### ISSUE THREAD

**Issue by TeamDDG** [twizmwazin/CardinalPGM#942]
Log : http://pastebin.com/gu73uGZ9

**Comment by Alfalik** [comment]
@TeamDDG Please. The readme clearly says this when creating an issue:
+ Have a demonstration of the bug or clear instructions to produce it.
+ Include the version of the plugin the issue is found on. The version can be found by typing /cardinal -v.
+ Make sure the report uses clear and concise English. By following these guidelines, it will help developers to quickly and accurately resolve the issue.

You can always use http://pastebin.com to upload logs or XML.

**Comment by Pablete1234** [comment]
@Alfalik actually the error says enough, it has something to do with the invisible blocks module (iron doors to barrier blocks, and block 36 removed for lag)
What sportbukkit version are you using? error says org.bukkit.Chunk.getBlocks does not exist...

**Comment by TeamDDG** [comment]
1.8.8

**Comment by Alfalik** [comment]
@TeamDDG There's no 1.8.8 version of Sportbukkit. Try using <a href="https://repo.oc.tc/#nexus-search;quick~sportbukkit">this</a> version (1.8.7), then do some tests on your server. Tell us, to actually understand the issue.

**Comment by TeamDDG** [comment]
it works now Ty!
