### ISSUE TITLE
Download?

### ISSUE THREAD

**Issue by GChevy** [twizmwazin/CardinalPGM#97]
Can i download the alpha version? I didn't find a download to test the plugin

**Comment by iEli2tyree011** [comment]
Until we have an official release, please use the wiki guide to help you compile the plugin.

**Comment by iEli2tyree011** [comment]
https://github.com/twizmwazin/CardinalPGM/wiki

**Comment by AngelCasillas01** [comment]
we should copy and paste all files D: or wut?

**Comment by twizmwazin** [comment]
You would need to be more specific. The guide should be sufficient information to compile a development version. The reason why we do not have a download yet is because Cardinal is not finished. When Cardinal is complete and we have fixed as many bugs as we can, there will be a 1.0 release with an easy download. However, until then if you wish to use an unsupported development version and keep it up-to-date for testing purposes, you will need to follow the guide. 

In English : https://github.com/twizmwazin/CardinalPGM/wiki/Installing-CardinalPGM
En español : https://github.com/twizmwazin/CardinalPGM/wiki/Instalando-CardinalPGM

**Comment by GChevy** [comment]
Thank you guys!!! Really nice work

**Comment by iJorGeZz** [comment]
A public build server if someone is interested in: http://build.ijorgezz.cf:8080/job/CardinalPGM/

**Comment by twizmwazin** [comment]
@iJorGeZz I'm not fond of your fork. While I can't stop you from having it, do not advertise it on my repository.

**Comment by iJorGeZz** [comment]
@twizmwazin I should have explained what is my purpose before posting that. In my fork I have two branches, one of them is the 'master' in which I thought not to do modifications apart from keep it updated and the second in which I do what it's name means. My idea was keep a jenkins public server for all, where you can find the <u>original</u> 'CardinalPGM'. That means that all those people who don't know how to compile or all those who don't feel like can download the last release. My intention never was advertise my fork. If you think this could be useful then we could hook the repository rather than my fork. Have a nice day.

**Comment by twizmwazin** [comment]
@iJorGeZz The thing is, there is no "latest release" just yet, as there is no official release yet. I have no downloads because I expect that people who are using this development preview have some basic technical knowledge. I will have my own jenkins server running soon though.
